name: Monitor Binance Listings

on:
  schedule:
    - cron: '59*1'  # Every 10 minutes
  workflow_dispatch:        # Allows manual triggering

permissions:
  contents: write          # Explicitly set permissions

jobs:
  check-listings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
          
      - name: Initialize JSON files
        run: |
          if [ ! -f binance_symbols.json ]; then
            echo "[]" > binance_symbols.json
          fi
          if [ ! -f new_symbols.json ]; then
            echo "[]" > new_symbols.json
          fi
          
      - name: Run Binance monitor
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python binance_monitor.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add binance_symbols.json new_symbols.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update symbol data" && git push)
